# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - 'lib/tasks/*.rake'
    - '**/config.ru'
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/*'
    - 'config/**/*.yml'
    - 'db/**/*'
    - 'script/**/*'
    - '.internal_test_app/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/internal/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

# DLSS configuration changes for these cops enabled by default in Rubocop

Layout/IndentationConsistency:
  EnforcedStyle: rails

Metrics/AbcSize:
  Max: 20

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 200

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

# DLSS explicitly disabling these cops enabled by default in Rubocop
# (DLSS agrees they should be disabled, or we disagree about whether they should be enabled)

Layout/AccessModifierIndentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/FilePath:
  Enabled: false
